name: Compile Keymap

on:
  push:
    branches:
      - 'keyboard/*'  # Trigger workflow for branches prefixed with 'keyboard/'
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Extract keyboard and keymap from branch name
      - name: Extract Keyboard and Keymap
        id: extract
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          IFS='/' read -r -a PARTS <<< "$BRANCH_NAME"
          echo "keyboard=${PARTS[1]}" >> $GITHUB_ENV
          echo "keymap=${PARTS[2]}" >> $GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.ref }}

      # Step 3: Install QMK dependencies
      - name: Install QMK Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip git gcc-avr avr-libc gcc-arm-none-eabi binutils-arm-none-eabi libusb-dev dfu-programmer dfu-util
          pip install qmk

      # Step 4: Set up QMK firmware
      - name: Set up QMK Firmware
        run: |
          qmk setup --yes
          qmk doctor

      # Step 5: Compile Firmware
      - name: Compile Firmware
        run: qmk compile -e CONVERT_TO=promicro_rp2040 -kb ${{ env.keyboard }} -km ${{ env.keymap }}

      # Step 6: Upload Firmware Artifact
      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware-${{ env.keyboard }}-${{ env.keymap }}
          path: |
            .build/*.hex
            .build/*.bin
