name: Compile Keymap

on:
  push:
    branches:
      - 'keyboard/*'
  workflow_dispatch:
    inputs:
      keyboard:
        description: 'Keyboard path (e.g., splitkb/aurora/lily58/rev1)'
        required: true
      keymap:
        description: 'Keymap name (e.g., Symphony)'
        required: true

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.version_tag.outputs.tag_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Version Tag
        id: version_tag
        run: |
          TAG_NAME="v$(date +'%Y.%m.%d')"
          echo "Generated Tag Name: $TAG_NAME"
          echo "::set-output name=tag_name::$TAG_NAME"

      - name: Prepare Firmware Directory
        run: |
          mkdir -p firmware
          mv build_artifacts/* firmware/

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: firmware/
          if-no-files-found: warn

  release:
    needs: build-and-upload
    runs-on: ubuntu-latest

    steps:
      - name: Download Firmware Artifact
        uses: actions/download-artifact@v3
        with:
          name: firmware
          path: ./firmware

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build-and-upload.outputs.tag_name }}
          release_name: Firmware Release - ${{ needs.build-and-upload.outputs.tag_name }}
          body: |
            Compiled firmware released on ${{ needs.build-and-upload.outputs.tag_name }}.
          draft: false
          prerelease: false
          files: ./firmware/*
